[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1A73E8"
backgroundColor = "#F8F9FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202124"
font = "sans serif"
